title :  Activate disneyplus.com/begin account on TV
description : <a href="http://actmynow.s3-website-us-west-1.amazonaws.com"><img src="/get-st.png"alt="disneyplus.com/begin"/></a>
google_analytics: UA-279844558-1
theme:  jekyll-theme-cayman
